name: Manual workflows

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and generate Crypto bindings
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-linux-androideabi
          - i686-linux-android   
          - aarch64-linux-android
    defaults:
      run:
        working-directory: ./rust-sdk-crypto
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: uniffi_bindgen    
      - uses: malinskiy/action-android/install-sdk@release/0.1.2
      - run: sdkmanager --install "ndk;22.0.7026061"
      - run: echo $ANDROID_HOME
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./rust-sdk-crypto/Cargo.toml --target aarch64-linux-android
      
